---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels: {component: draino}
  name: draino
  namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    component: draino
  name: draino
rules:
  - apiGroups: ['']
    resources: [events]
    verbs: [create, patch, update]
  - apiGroups: ['']
    resources: [nodes]
    verbs: [get, watch, list, update, patch]
  - apiGroups: ['']
    resources: [nodes/status]
    verbs: [get, watch, list, update, patch]
  - apiGroups: ['']
    resources: [endpoints]
    verbs: [get, watch, list, create, patch, update]
  - apiGroups: ['']
    resources: [pods]
    verbs: [get, watch, list]
  - apiGroups: ['']
    resources: [pods/eviction]
    verbs: [create]
  - apiGroups:
      - extensions
      - apps
    resources: [daemonsets]
    verbs: [get, watch, list]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels: {component: draino}
  name: draino
roleRef: {apiGroup: rbac.authorization.k8s.io, kind: ClusterRole, name: draino}
subjects:
- {kind: ServiceAccount, name: draino, namespace: kube-system}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {component: draino}
  name: draino
  namespace: kube-system
spec:
  # Draino does not currently support locking/master election, so you should
  # only run one draino at a time. Draino won't start draining nodes immediately
  # so it's usually safe for multiple drainos to exist for a brief period of
  # time.
  replicas: 1
  selector:
    matchLabels: {component: draino}
  template:
    metadata:
      labels: {component: draino}
      name: draino
      namespace: kube-system
    spec:
      containers:
      # You'll want to change these labels and conditions to suit your deployment.
      - command: [/draino, --dry-run, --node-label=draino-enabled=true, BadCondition, ReallyBadCondition]
        image: planetlabs/draino:5e07e93
        livenessProbe:
          httpGet: {path: /healthz, port: 10002}
          initialDelaySeconds: 30
        name: draino
      serviceAccountName: draino
