{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "draino.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "draino.name" . }}
    helm.sh/chart: {{ include "draino.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups: ['']
  resources: [events]
  verbs: [create, patch, update]
- apiGroups: ['']
  resources: [nodes]
  verbs: [get, watch, list, update]
- apiGroups: ['']
  resources: [nodes/status]
  verbs: [patch, update]
- apiGroups: ['']
  resources: [pods]
  verbs: [get, watch, list]
- apiGroups: ['']
  resources: [pods/eviction]
  verbs: [create]
- apiGroups: [apps]
  resources: [daemonsets]
  verbs: [get, watch, list]
- apiGroups: ['*']
  resources: [statefulsets]
  verbs: [get]
- apiGroups: ['']
  resources: [endpoints]
  verbs: [get, create, update]

{{- end -}}
